-- name: CreateTenant :one
INSERT INTO tenants (name, daily_sms_limit, monthly_budget)
VALUES ($1, $2, $3)
RETURNING *;

-- name: GetTenantByID :one
SELECT * FROM tenants WHERE id = $1;

-- name: ListTenants :many
SELECT * FROM tenants ORDER BY id;

-- name: SetTenantStatus :exec
UPDATE tenants SET status = $2, updated_at = now() WHERE id = $1;

-- name: CreateAPIKey :one
INSERT INTO api_keys (tenant_id, prefix, hash, name)
VALUES ($1, $2, $3, $4)
RETURNING *;

-- name: GetAPIKeyByPrefix :one
SELECT * FROM api_keys WHERE prefix = $1;

-- name: ListAPIKeysByTenant :many
SELECT * FROM api_keys WHERE tenant_id = $1 ORDER BY id DESC;

-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL;

-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1;

-- name: CreateAdminUser :one
INSERT INTO admin_users (email, password_hash, role)
VALUES ($1, $2, $3)
RETURNING *;

-- name: GetAdminUserByEmail :one
SELECT * FROM admin_users WHERE email = $1;

-- name: ListAdminUsers :many
SELECT * FROM admin_users ORDER BY id;

-- name: CountAdminUsers :one
SELECT COUNT(*) FROM admin_users;

-- name: AppendAuditLog :exec
INSERT INTO audit_log (actor_id, action, target_type, target_id, metadata)
VALUES ($1, $2, $3, $4, $5);

-- name: CreateMessage :one
INSERT INTO messages (
    id, tenant_id, sender, recipient, text, dcs, num_parts, status, client_ref
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 'queued', $8
)
RETURNING *;

-- name: GetMessageForTenant :one
SELECT * FROM messages WHERE id = $1 AND tenant_id = $2;

-- name: ListMessagesByTenant :many
SELECT * FROM messages
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2;

-- name: ClaimQueuedMessage :one
UPDATE messages
SET status = 'sending',
    claimed_at = now(),
    attempts = attempts + 1
WHERE id = (
    SELECT id FROM messages
    WHERE status = 'queued' AND next_attempt_at <= now()
    ORDER BY next_attempt_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING *;

-- name: MarkMessageSent :exec
UPDATE messages
SET status = 'sent',
    horisen_msg_id = $2,
    sent_at = now(),
    claimed_at = NULL
WHERE id = $1;

-- name: MarkMessageRejected :exec
UPDATE messages
SET status = 'rejected',
    error_code = $2,
    error_message = $3,
    final_at = now(),
    claimed_at = NULL
WHERE id = $1;

-- name: BumpMessageRetry :exec
UPDATE messages
SET status = 'queued',
    next_attempt_at = $2,
    error_code = $3,
    error_message = $4,
    claimed_at = NULL
WHERE id = $1;

-- name: RecoverStaleSending :exec
UPDATE messages
SET status = 'queued', claimed_at = NULL
WHERE status = 'sending' AND claimed_at < $1;

-- ApplyDLR updates a message based on a Horisen DLR. We only touch messages
-- in non-final states (sent, queued, sending) so a late or duplicate DLR
-- can't clobber an existing terminal state. RETURNING tells the caller
-- whether the update actually happened.
--
-- name: ApplyDLR :one
UPDATE messages
SET status = $2,
    error_code = COALESCE($3, error_code),
    error_message = COALESCE($4, error_message),
    horisen_msg_id = COALESCE(horisen_msg_id, $5),
    final_at = CASE WHEN $2 IN ('delivered','undelivered','rejected','failed')
                    THEN now() ELSE final_at END
WHERE id = $1
  AND status NOT IN ('delivered','undelivered','rejected','failed')
RETURNING id, tenant_id, status;

-- GetMessageByHorisenMsgID is the fallback lookup for DLRs that carry the
-- Horisen msgId but no custom.msgId — for example DLRs generated by jobs
-- submitted before custom.msgId was being set.
--
-- name: GetMessageByHorisenMsgID :one
SELECT id, tenant_id, status FROM messages
WHERE horisen_msg_id = $1
ORDER BY created_at DESC
LIMIT 1;

-- ===== webhook_endpoints =====

-- name: CreateWebhookEndpoint :one
INSERT INTO webhook_endpoints (tenant_id, url, secret, events, active)
VALUES ($1, $2, $3, $4, true)
RETURNING *;

-- name: GetWebhookEndpoint :one
SELECT * FROM webhook_endpoints WHERE id = $1 AND tenant_id = $2;

-- name: ListWebhookEndpointsByTenant :many
SELECT * FROM webhook_endpoints WHERE tenant_id = $1 ORDER BY id DESC;

-- name: ListActiveEndpointsForEvent :many
-- Returns all active endpoints for a tenant that have subscribed to the
-- given event type. Used by the DLR/MO fan-out path.
SELECT * FROM webhook_endpoints
WHERE tenant_id = sqlc.arg(tenant_id)
  AND active
  AND sqlc.arg(event_type)::text = ANY(events);

-- name: SetWebhookEndpointActive :exec
UPDATE webhook_endpoints SET active = $3 WHERE id = $1 AND tenant_id = $2;

-- name: DeleteWebhookEndpoint :exec
DELETE FROM webhook_endpoints WHERE id = $1 AND tenant_id = $2;

-- ===== webhook_deliveries =====

-- name: EnqueueWebhookDelivery :one
INSERT INTO webhook_deliveries (
    endpoint_id, tenant_id, event_id, event_type, payload, status, next_attempt_at
) VALUES (
    $1, $2, $3, $4, $5, 'pending', now()
)
RETURNING *;

-- name: ClaimPendingDelivery :one
-- Atomically pick one ready delivery and mark it in_flight so other workers
-- skip it. attempts is bumped here so even crashes leave a trail.
UPDATE webhook_deliveries
SET status = 'in_flight',
    claimed_at = now(),
    attempts = attempts + 1
WHERE id = (
    SELECT id FROM webhook_deliveries
    WHERE status IN ('pending','failed') AND next_attempt_at <= now()
    ORDER BY next_attempt_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING *;

-- name: MarkDeliverySuccess :exec
UPDATE webhook_deliveries
SET status = 'success',
    delivered_at = now(),
    last_status = $2,
    last_error = NULL,
    last_response = $3,
    claimed_at = NULL
WHERE id = $1;

-- name: MarkDeliveryFailed :exec
-- Used for both "retry later" (status=failed) and terminal "dead".
UPDATE webhook_deliveries
SET status = $2,
    next_attempt_at = $3,
    last_status = $4,
    last_error = $5,
    last_response = $6,
    claimed_at = NULL
WHERE id = $1;

-- name: RecoverStaleWebhookDeliveries :exec
-- Reset rows stuck in_flight beyond the cutoff so a crashed worker doesn't
-- pin them forever.
UPDATE webhook_deliveries
SET status = 'pending', claimed_at = NULL
WHERE status = 'in_flight' AND claimed_at < $1;

-- name: ListDeliveriesForEndpoint :many
SELECT * FROM webhook_deliveries
WHERE endpoint_id = $1 AND tenant_id = $2
ORDER BY created_at DESC
LIMIT $3;

-- ===== inbound_numbers =====

-- name: CreateInboundNumber :one
INSERT INTO inbound_numbers (msisdn, tenant_id, label)
VALUES ($1, $2, $3)
RETURNING *;

-- name: GetInboundNumber :one
SELECT * FROM inbound_numbers WHERE msisdn = $1;

-- name: ListInboundNumbersByTenant :many
SELECT * FROM inbound_numbers WHERE tenant_id = $1 ORDER BY msisdn;

-- name: ListInboundNumbersAll :many
SELECT * FROM inbound_numbers ORDER BY tenant_id, msisdn;

-- name: DeleteInboundNumber :exec
DELETE FROM inbound_numbers WHERE msisdn = $1;

-- ===== inbound_messages =====

-- name: CreateInboundMessage :one
-- ON CONFLICT on horisen_id makes the insert idempotent: a duplicate MO
-- callback returns the existing row instead of failing.
INSERT INTO inbound_messages (id, tenant_id, horisen_id, src, dst, text, dcs, received_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (horisen_id) DO UPDATE SET horisen_id = EXCLUDED.horisen_id
RETURNING *;

-- name: GetInboundMessage :one
SELECT * FROM inbound_messages WHERE id = $1 AND tenant_id = $2;

-- name: ListInboundMessagesByTenant :many
SELECT * FROM inbound_messages
WHERE tenant_id = $1
ORDER BY received_at DESC
LIMIT $2;

-- ===== events (polling feed) =====

-- name: CreateEvent :one
INSERT INTO events (tenant_id, type, payload)
VALUES ($1, $2, $3)
RETURNING *;

-- name: ListEventsByTenant :many
-- cursor_id = 0 means "from newest"; types NULL/empty array means no type filter.
SELECT * FROM events
WHERE tenant_id = sqlc.arg(tenant_id)
  AND (sqlc.arg(cursor_id)::bigint = 0 OR id < sqlc.arg(cursor_id)::bigint)
  AND (sqlc.narg(types)::text[] IS NULL OR type = ANY(sqlc.narg(types)::text[]))
  AND (sqlc.narg(from_time)::timestamptz IS NULL OR created_at >= sqlc.narg(from_time)::timestamptz)
  AND (sqlc.narg(to_time)::timestamptz   IS NULL OR created_at <  sqlc.narg(to_time)::timestamptz)
ORDER BY id DESC
LIMIT sqlc.arg(lim);

-- name: ListMessagesFiltered :many
-- Cursor is (created_at, id) tuple — id is UUID v4 so not monotonic on its own.
-- nullable cursor_created_at (and matching cursor_id) means "from newest".
SELECT * FROM messages
WHERE tenant_id = sqlc.arg(tenant_id)
  AND (sqlc.narg(cursor_created_at)::timestamptz IS NULL
       OR (created_at, id) < (sqlc.narg(cursor_created_at)::timestamptz, sqlc.narg(cursor_id)::uuid))
  AND (sqlc.narg(status)::text     IS NULL OR status     = sqlc.narg(status)::text)
  AND (sqlc.narg(recipient)::text  IS NULL OR recipient  = sqlc.narg(recipient)::text)
  AND (sqlc.narg(client_ref)::text IS NULL OR client_ref = sqlc.narg(client_ref)::text)
  AND (sqlc.narg(from_time)::timestamptz IS NULL OR created_at >= sqlc.narg(from_time)::timestamptz)
  AND (sqlc.narg(to_time)::timestamptz   IS NULL OR created_at <  sqlc.narg(to_time)::timestamptz)
ORDER BY created_at DESC, id DESC
LIMIT sqlc.arg(lim);
